name: MacOS
on: [push, pull_request]
jobs:
  test:
    name: MacOS ${{ matrix.node-version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12, 14, 16, 17]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run mocha_napi
