name: Node
on: [push]
jobs:
  test:
    name: Node ${{ matrix.node-version }} . ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8, 10, 12, 13] # 6 fails on MacOSX
        os: [ubuntu-latest, macOS-latest] # windows-latest fails
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: npm i
      run: npm test
      env:
        CI: true
